#!/usr/bin/env bash

lock_script="/home/reese/scripts/lock"
term_art=(
	"pipes-rs"
	"cbonsai -li -L36 -M6 --seed=\$(date +'%N')"
	"cmatrix -ark"
	"asciiquarium"
)

case "$1" in
	start )
		$(readlink -f $0) stop # just in case it was already running
		KITTY_ID=$RANDOM
		echo $KITTY_ID > $HOME/.cache/screensaver-kitty-id
		KITTY_ID=$KITTY_ID kitty-popup fullscreen -c "${term_art[RANDOM%${#term_art[@]}]}"
		;;
	stop )
		read -r KITTY_ID <<< `cat $HOME/.cache/screensaver-kitty-id`
		kitty @ --to unix:/tmp/kitty-popup_$KITTY_ID close-window
		;;
	watch )
		# The actual screensaver timer, starts after 30min
		xidlehook --not-when-fullscreen \
			--socket /tmp/xidlehook0.socket \
			--timer 1800 \
				"$(readlink -f $0) start" \
				"$lock_script && $(readlink -f $0) stop" &

		# Sleep timer, starts after 1h
		xidlehook --not-when-fullscreen \
			--socket /tmp/xidlehook1.socket \
			--timer 3600 \
				"$lock_script && $(readlink -f $0) stop && sudo systemctl suspend" "" &
		;;
esac
