#!/usr/bin/env bash

# Display layout menu

mode_laptop () {
	xrandr --output eDP-1-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1-1 --off
	cleanup
}
mode_ultrawide () {
	xrandr --output eDP-1-1 --off --output DP-1-1 --primary --mode 3440x1440 --pos 0x0 --rotate normal
	cleanup
}

cleanup () {
	pywal -a
}

options=$'ultrawide\nlaptop'
eval mode_$(echo "$options" | rofi -dmenu -p 'display layout' -lines 2)
