#!/usr/bin/env bash

# Options
shutdown=""
reboot=""
lock=""
suspend=""
logout=""

options="$suspend\n$lock\n$logout\n$shutdown\n$reboot"

result=$(echo -e "$options" | rofi -dmenu -config ~/.config/rofi/powermenu.rasi)

case $result in
	$suspend )
		/home/reese/scripts/lock
		systemctl suspend
		break ;;
	$lock )
		/home/reese/scripts/lock
		break ;;
	$logout )
		i3-msg exit
		break ;;
	$shutdown )
		systemctl poweroff
		break ;;
	$reboot )
		systemctl reboot
		break ;;
esac
